---
- name: configure ip-helpers with a loop
  connection: network_cli
  hosts: all
  tasks: 
    - name: configure ip-helpers
      ios_config: 
        lines: 
          - ip helper-address 172.16.1.100
        parents: "{{ item }}"
      with_items: 
        - interface GigabitEthernet1

...
